config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
    resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	 validates :title, presence: true
	 validates :author, presence: true
	 validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new	
	end

	def edit
		@post = Post.find(params[:id])
	end

	def destroy
		Post.find(params[:id]).destroy
		redirect_to root_path
	end

	def show
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])
		post.assign_attributes(post_params)
		if post.save
			redirect_to root_path
		else
			redirect_to edit_post_path(post.id)
		end
	end

	def create
		post = Post.new(post_params)
		if post.save
			redirect_to post
		else
			redirect_to new_post_path
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :author, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for (@post) do |f| %>
	
  Title: <%= f.text_field :title %><br />
  Author : <%= f.text_field :author %><br />
  Content : <%= f.text_area :content %><br />
  
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<%= link_to 'New post', new_post_path %>

<% @posts.each do |post| %>
	<h1> <%= post.title %></h1>
	<h3> <%= post.author %> </h3>
	<p> <%= post.content %> </p>
	<p><%= link_to 'Show', post_path(post.id) %></p>
	<p><%= link_to 'Edit', edit_post_path(post.id) %></p>
	<p><%= link_to 'Delete', post, method: :delete %></p>
<% end %>

app/views/posts/new.html.erb
<%= form_for (Post.new) do |f| %>
	
  Title: <%= f.text_field :title %><br />
  Author : <%= f.text_field :author %><br />
  Content : <%= f.text_area :content %><br />
  
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
	<h1> <%= @post.title %></h1>
	<h3> <%= @post.author %> </h3>
	<p> <%= @post.content %> </p>

	<%=link_to 'Back to list', root_path %>